# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.storage_api import StorageApi  # noqa: E501
from fdtapi.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.storage_api.StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_storage_providers(self):
        """Test case for get_storage_providers

        """
        pass


if __name__ == '__main__':
    unittest.main()
