# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.wallet_api import WalletApi  # noqa: E501
from fdtapi.rest import ApiException


class TestWalletApi(unittest.TestCase):
    """WalletApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.wallet_api.WalletApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_seqno(self):
        """Test case for get_account_seqno

        """
        pass

    def test_get_wallet_backup(self):
        """Test case for get_wallet_backup

        """
        pass

    def test_get_wallets_by_public_key(self):
        """Test case for get_wallets_by_public_key

        """
        pass

    def test_set_wallet_backup(self):
        """Test case for set_wallet_backup

        """
        pass

    def test_ton_connect_proof(self):
        """Test case for ton_connect_proof

        """
        pass


if __name__ == '__main__':
    unittest.main()
