# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.lite_server_api import LiteServerApi  # noqa: E501
from fdtapi.rest import ApiException


class TestLiteServerApi(unittest.TestCase):
    """LiteServerApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.lite_server_api.LiteServerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_raw_shards_info(self):
        """Test case for get_all_raw_shards_info

        """
        pass

    def test_get_raw_account_state(self):
        """Test case for get_raw_account_state

        """
        pass

    def test_get_raw_block_proof(self):
        """Test case for get_raw_block_proof

        """
        pass

    def test_get_raw_blockchain_block(self):
        """Test case for get_raw_blockchain_block

        """
        pass

    def test_get_raw_blockchain_block_header(self):
        """Test case for get_raw_blockchain_block_header

        """
        pass

    def test_get_raw_blockchain_block_state(self):
        """Test case for get_raw_blockchain_block_state

        """
        pass

    def test_get_raw_config(self):
        """Test case for get_raw_config

        """
        pass

    def test_get_raw_list_block_transactions(self):
        """Test case for get_raw_list_block_transactions

        """
        pass

    def test_get_raw_masterchain_info(self):
        """Test case for get_raw_masterchain_info

        """
        pass

    def test_get_raw_masterchain_info_ext(self):
        """Test case for get_raw_masterchain_info_ext

        """
        pass

    def test_get_raw_shard_block_proof(self):
        """Test case for get_raw_shard_block_proof

        """
        pass

    def test_get_raw_shard_info(self):
        """Test case for get_raw_shard_info

        """
        pass

    def test_get_raw_time(self):
        """Test case for get_raw_time

        """
        pass

    def test_get_raw_transactions(self):
        """Test case for get_raw_transactions

        """
        pass

    def test_send_raw_message(self):
        """Test case for send_raw_message

        """
        pass


if __name__ == '__main__':
    unittest.main()
