# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.storage_provider import StorageProvider  # noqa: E501
from fdtapi.rest import ApiException

class TestStorageProvider(unittest.TestCase):
    """StorageProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StorageProvider
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StorageProvider`
        """
        model = fdtapi.models.storage_provider.StorageProvider()  # noqa: E501
        if include_optional :
            return StorageProvider(
                address = '0:FD595F36B4C1535BEC8461490D38EBB9AE3C38DD6ACE17CA63ABE2C6608BE159', 
                accept_new_contracts = True, 
                rate_per_mb_day = 50000000, 
                max_span = 604800, 
                minimal_file_size = 64, 
                maximal_file_size = 10485760
            )
        else :
            return StorageProvider(
                address = '0:FD595F36B4C1535BEC8461490D38EBB9AE3C38DD6ACE17CA63ABE2C6608BE159',
                accept_new_contracts = True,
                rate_per_mb_day = 50000000,
                max_span = 604800,
                minimal_file_size = 64,
                maximal_file_size = 10485760,
        )
        """

    def testStorageProvider(self):
        """Test StorageProvider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
