# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.jetton_transfer_action import JettonTransferAction  # noqa: E501
from fdtapi.rest import ApiException

class TestJettonTransferAction(unittest.TestCase):
    """JettonTransferAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JettonTransferAction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JettonTransferAction`
        """
        model = fdtapi.models.jetton_transfer_action.JettonTransferAction()  # noqa: E501
        if include_optional :
            return JettonTransferAction(
                sender = fdtapi.models.account_address.AccountAddress(
                    address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365', 
                    name = 'Ton foundation', 
                    is_scam = True, 
                    icon = 'https://ton.org/logo.png', ), 
                recipient = fdtapi.models.account_address.AccountAddress(
                    address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365', 
                    name = 'Ton foundation', 
                    is_scam = True, 
                    icon = 'https://ton.org/logo.png', ), 
                senders_wallet = '0:E93E7D444180608B8520C00DC664383A387356FB6E16FDDF99DBE5E1415A574B', 
                recipients_wallet = '0:E93E7D444180608B8520C00DC664383A387356FB6E16FDDF99DBE5E1415A574B', 
                amount = '1000000000', 
                comment = 'Hi! This is your salary. 
From accounting with love.', 
                encrypted_comment = fdtapi.models.encrypted_comment.EncryptedComment(
                    encryption_type = 'simple', 
                    cipher_text = 'A6A0BD6608672B...CE3AF8DB', ), 
                refund = fdtapi.models.refund.Refund(
                    type = 'DNS.ton', 
                    origin = '0:da6b1b6663a0e4d18cc8574ccd9db5296e367dd9324706f3bbd9eb1cd2caf0bf', ), 
                jetton = fdtapi.models.jetton_preview.JettonPreview(
                    address = '0:0BB5A9F69043EEBDDA5AD2E946EB953242BD8F603FE795D90698CEEC6BFC60A0', 
                    name = 'Wrapped TON', 
                    symbol = 'WTON', 
                    decimals = 9, 
                    image = 'https://cache.tonapi.io/images/jetton.jpg', 
                    verification = 'whitelist', )
            )
        else :
            return JettonTransferAction(
                senders_wallet = '0:E93E7D444180608B8520C00DC664383A387356FB6E16FDDF99DBE5E1415A574B',
                recipients_wallet = '0:E93E7D444180608B8520C00DC664383A387356FB6E16FDDF99DBE5E1415A574B',
                amount = '1000000000',
                jetton = fdtapi.models.jetton_preview.JettonPreview(
                    address = '0:0BB5A9F69043EEBDDA5AD2E946EB953242BD8F603FE795D90698CEEC6BFC60A0', 
                    name = 'Wrapped TON', 
                    symbol = 'WTON', 
                    decimals = 9, 
                    image = 'https://cache.tonapi.io/images/jetton.jpg', 
                    verification = 'whitelist', ),
        )
        """

    def testJettonTransferAction(self):
        """Test JettonTransferAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
