# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.encrypted_comment import EncryptedComment  # noqa: E501
from fdtapi.rest import ApiException

class TestEncryptedComment(unittest.TestCase):
    """EncryptedComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EncryptedComment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EncryptedComment`
        """
        model = fdtapi.models.encrypted_comment.EncryptedComment()  # noqa: E501
        if include_optional :
            return EncryptedComment(
                encryption_type = 'simple', 
                cipher_text = 'A6A0BD6608672B...CE3AF8DB'
            )
        else :
            return EncryptedComment(
                encryption_type = 'simple',
                cipher_text = 'A6A0BD6608672B...CE3AF8DB',
        )
        """

    def testEncryptedComment(self):
        """Test EncryptedComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
