# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.credit_phase import CreditPhase  # noqa: E501
from fdtapi.rest import ApiException

class TestCreditPhase(unittest.TestCase):
    """CreditPhase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreditPhase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditPhase`
        """
        model = fdtapi.models.credit_phase.CreditPhase()  # noqa: E501
        if include_optional :
            return CreditPhase(
                fees_collected = 100, 
                credit = 1000
            )
        else :
            return CreditPhase(
                fees_collected = 100,
                credit = 1000,
        )
        """

    def testCreditPhase(self):
        """Test CreditPhase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
