# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.jettons_api import JettonsApi  # noqa: E501
from fdtapi.rest import ApiException


class TestJettonsApi(unittest.TestCase):
    """JettonsApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.jettons_api.JettonsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_jetton_info(self):
        """Test case for get_jetton_info

        """
        pass

    def test_get_jettons(self):
        """Test case for get_jettons

        """
        pass


if __name__ == '__main__':
    unittest.main()
