# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.connect_api import ConnectApi  # noqa: E501
from fdtapi.rest import ApiException


class TestConnectApi(unittest.TestCase):
    """ConnectApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.connect_api.ConnectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_info_by_state_init(self):
        """Test case for get_account_info_by_state_init

        """
        pass

    def test_get_ton_connect_payload(self):
        """Test case for get_ton_connect_payload

        """
        pass


if __name__ == '__main__':
    unittest.main()
