# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.nft_item_collection import NftItemCollection  # noqa: E501
from fdtapi.rest import ApiException

class TestNftItemCollection(unittest.TestCase):
    """NftItemCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NftItemCollection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NftItemCollection`
        """
        model = fdtapi.models.nft_item_collection.NftItemCollection()  # noqa: E501
        if include_optional :
            return NftItemCollection(
                address = '0:E93E7D444180608B8520C00DC664383A387356FB6E16FDDF99DBE5E1415A574B', 
                name = 'TON Diamonds', 
                description = 'Best collection in TON network'
            )
        else :
            return NftItemCollection(
                address = '0:E93E7D444180608B8520C00DC664383A387356FB6E16FDDF99DBE5E1415A574B',
                name = 'TON Diamonds',
                description = 'Best collection in TON network',
        )
        """

    def testNftItemCollection(self):
        """Test NftItemCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
