# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.nft_collections import NftCollections  # noqa: E501
from fdtapi.rest import ApiException

class TestNftCollections(unittest.TestCase):
    """NftCollections unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NftCollections
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NftCollections`
        """
        model = fdtapi.models.nft_collections.NftCollections()  # noqa: E501
        if include_optional :
            return NftCollections(
                nft_collections = [
                    fdtapi.models.nft_collection.NftCollection(
                        address = '0:FD595F36B4C1535BEC8461490D38EBB9AE3C38DD6ACE17CA63ABE2C6608BE159', 
                        next_item_index = 1, 
                        owner = fdtapi.models.account_address.AccountAddress(
                            address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365', 
                            name = 'Ton foundation', 
                            is_scam = True, 
                            icon = 'https://ton.org/logo.png', ), 
                        raw_collection_content = '697066733a2f2f516d596e437861746f5178433571584b79773971656768415853626f3544644e6a32387631487669437a47355359', 
                        metadata = {}, )
                    ]
            )
        else :
            return NftCollections(
                nft_collections = [
                    fdtapi.models.nft_collection.NftCollection(
                        address = '0:FD595F36B4C1535BEC8461490D38EBB9AE3C38DD6ACE17CA63ABE2C6608BE159', 
                        next_item_index = 1, 
                        owner = fdtapi.models.account_address.AccountAddress(
                            address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365', 
                            name = 'Ton foundation', 
                            is_scam = True, 
                            icon = 'https://ton.org/logo.png', ), 
                        raw_collection_content = '697066733a2f2f516d596e437861746f5178433571584b79773971656768415853626f3544644e6a32387631487669437a47355359', 
                        metadata = {}, )
                    ],
        )
        """

    def testNftCollections(self):
        """Test NftCollections"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
