# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.dns_api import DNSApi  # noqa: E501
from fdtapi.rest import ApiException


class TestDNSApi(unittest.TestCase):
    """DNSApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.dns_api.DNSApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dns_resolve(self):
        """Test case for dns_resolve

        """
        pass

    def test_get_all_auctions(self):
        """Test case for get_all_auctions

        """
        pass

    def test_get_dns_info(self):
        """Test case for get_dns_info

        """
        pass

    def test_get_domain_bids(self):
        """Test case for get_domain_bids

        """
        pass


if __name__ == '__main__':
    unittest.main()
