# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.bounce_phase_type import BouncePhaseType  # noqa: E501
from fdtapi.rest import ApiException

class TestBouncePhaseType(unittest.TestCase):
    """BouncePhaseType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBouncePhaseType(self):
        """Test BouncePhaseType"""
        # inst = BouncePhaseType()

if __name__ == '__main__':
    unittest.main()
