# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.accounts_api import AccountsApi  # noqa: E501
from fdtapi.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_dns_back_resolve(self):
        """Test case for account_dns_back_resolve

        """
        pass

    def test_get_account(self):
        """Test case for get_account

        """
        pass

    def test_get_account_diff(self):
        """Test case for get_account_diff

        """
        pass

    def test_get_account_dns_expiring(self):
        """Test case for get_account_dns_expiring

        """
        pass

    def test_get_account_event(self):
        """Test case for get_account_event

        """
        pass

    def test_get_account_events(self):
        """Test case for get_account_events

        """
        pass

    def test_get_account_jetton_history_by_id(self):
        """Test case for get_account_jetton_history_by_id

        """
        pass

    def test_get_account_jettons_balances(self):
        """Test case for get_account_jettons_balances

        """
        pass

    def test_get_account_jettons_history(self):
        """Test case for get_account_jettons_history

        """
        pass

    def test_get_account_nft_items(self):
        """Test case for get_account_nft_items

        """
        pass

    def test_get_account_public_key(self):
        """Test case for get_account_public_key

        """
        pass

    def test_get_account_subscriptions(self):
        """Test case for get_account_subscriptions

        """
        pass

    def test_get_account_traces(self):
        """Test case for get_account_traces

        """
        pass

    def test_get_accounts(self):
        """Test case for get_accounts

        """
        pass

    def test_reindex_account(self):
        """Test case for reindex_account

        """
        pass

    def test_search_accounts(self):
        """Test case for search_accounts

        """
        pass


if __name__ == '__main__':
    unittest.main()
