# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.get_accounts_request import GetAccountsRequest  # noqa: E501
from fdtapi.rest import ApiException

class TestGetAccountsRequest(unittest.TestCase):
    """GetAccountsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetAccountsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountsRequest`
        """
        model = fdtapi.models.get_accounts_request.GetAccountsRequest()  # noqa: E501
        if include_optional :
            return GetAccountsRequest(
                account_ids = [
                    '0:97264395BD65A255A429B11326C84128B7D70FFED7949ABAE3036D506BA38621'
                    ]
            )
        else :
            return GetAccountsRequest(
                account_ids = [
                    '0:97264395BD65A255A429B11326C84128B7D70FFED7949ABAE3036D506BA38621'
                    ],
        )
        """

    def testGetAccountsRequest(self):
        """Test GetAccountsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
