# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.traces_api import TracesApi  # noqa: E501
from fdtapi.rest import ApiException


class TestTracesApi(unittest.TestCase):
    """TracesApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.traces_api.TracesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_trace(self):
        """Test case for get_trace

        """
        pass


if __name__ == '__main__':
    unittest.main()
