# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.subscription import Subscription  # noqa: E501
from fdtapi.rest import ApiException

class TestSubscription(unittest.TestCase):
    """Subscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Subscription
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Subscription`
        """
        model = fdtapi.models.subscription.Subscription()  # noqa: E501
        if include_optional :
            return Subscription(
                address = '0:dea8f638b789172ce36d10a20318125e52c649aa84893cd77858224fe2b9b0ee', 
                wallet_address = '0:567DE86AF2B6A557D7085807CF7C26338124987A5179344F0D0FA2657EB710F1', 
                beneficiary_address = '0:c704dadfabac88eab58e340de03080df81ff76636431f48624ad6e26fb2da0a4', 
                amount = 1000000000, 
                period = 2592000, 
                start_time = 1653996832, 
                timeout = 10800, 
                last_payment_time = 1653996834, 
                last_request_time = 0, 
                subscription_id = 217477, 
                failed_attempts = 0
            )
        else :
            return Subscription(
                address = '0:dea8f638b789172ce36d10a20318125e52c649aa84893cd77858224fe2b9b0ee',
                wallet_address = '0:567DE86AF2B6A557D7085807CF7C26338124987A5179344F0D0FA2657EB710F1',
                beneficiary_address = '0:c704dadfabac88eab58e340de03080df81ff76636431f48624ad6e26fb2da0a4',
                amount = 1000000000,
                period = 2592000,
                start_time = 1653996832,
                timeout = 10800,
                last_payment_time = 1653996834,
                last_request_time = 0,
                subscription_id = 217477,
                failed_attempts = 0,
        )
        """

    def testSubscription(self):
        """Test Subscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
