# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.action_simple_preview import ActionSimplePreview  # noqa: E501
from fdtapi.rest import ApiException

class TestActionSimplePreview(unittest.TestCase):
    """ActionSimplePreview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ActionSimplePreview
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionSimplePreview`
        """
        model = fdtapi.models.action_simple_preview.ActionSimplePreview()  # noqa: E501
        if include_optional :
            return ActionSimplePreview(
                name = 'Ton Transfer', 
                description = 'Transferring 5 Ton', 
                action_image = '', 
                value = '5 Ton', 
                value_image = '', 
                accounts = [
                    fdtapi.models.account_address.AccountAddress(
                        address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365', 
                        name = 'Ton foundation', 
                        is_scam = True, 
                        icon = 'https://ton.org/logo.png', )
                    ]
            )
        else :
            return ActionSimplePreview(
                name = 'Ton Transfer',
                description = 'Transferring 5 Ton',
                accounts = [
                    fdtapi.models.account_address.AccountAddress(
                        address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365', 
                        name = 'Ton foundation', 
                        is_scam = True, 
                        icon = 'https://ton.org/logo.png', )
                    ],
        )
        """

    def testActionSimplePreview(self):
        """Test ActionSimplePreview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
