# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.send_blockchain_message_request import SendBlockchainMessageRequest  # noqa: E501
from fdtapi.rest import ApiException

class TestSendBlockchainMessageRequest(unittest.TestCase):
    """SendBlockchainMessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SendBlockchainMessageRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendBlockchainMessageRequest`
        """
        model = fdtapi.models.send_blockchain_message_request.SendBlockchainMessageRequest()  # noqa: E501
        if include_optional :
            return SendBlockchainMessageRequest(
                boc = 'te6ccgECBQEAARUAAkWIAWTtae+KgtbrX26Bep8JSq8lFLfGOoyGR/xwdjfvpvEaHg', 
                batch = [
                    'te6ccgECBQEAARUAAkWIAWTtae+KgtbrX26Bep8JSq8lFLfGOoyGR/xwdjfvpvEaHg'
                    ]
            )
        else :
            return SendBlockchainMessageRequest(
        )
        """

    def testSendBlockchainMessageRequest(self):
        """Test SendBlockchainMessageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
