# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.account_staking_info import AccountStakingInfo  # noqa: E501
from fdtapi.rest import ApiException

class TestAccountStakingInfo(unittest.TestCase):
    """AccountStakingInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AccountStakingInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountStakingInfo`
        """
        model = fdtapi.models.account_staking_info.AccountStakingInfo()  # noqa: E501
        if include_optional :
            return AccountStakingInfo(
                pool = 'EQBI-wGVp_x0VFEjd7m9cEUD3tJ_bnxMSp0Tb9qz757ATEAM', 
                amount = 10050000000000, 
                pending_deposit = 500000000000, 
                pending_withdraw = 500000000000, 
                ready_withdraw = 500000000000
            )
        else :
            return AccountStakingInfo(
                pool = 'EQBI-wGVp_x0VFEjd7m9cEUD3tJ_bnxMSp0Tb9qz757ATEAM',
                amount = 10050000000000,
                pending_deposit = 500000000000,
                pending_withdraw = 500000000000,
                ready_withdraw = 500000000000,
        )
        """

    def testAccountStakingInfo(self):
        """Test AccountStakingInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
