# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.ton_connect_proof_request_proof import TonConnectProofRequestProof  # noqa: E501
from fdtapi.rest import ApiException

class TestTonConnectProofRequestProof(unittest.TestCase):
    """TonConnectProofRequestProof unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TonConnectProofRequestProof
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TonConnectProofRequestProof`
        """
        model = fdtapi.models.ton_connect_proof_request_proof.TonConnectProofRequestProof()  # noqa: E501
        if include_optional :
            return TonConnectProofRequestProof(
                timestamp = 1678275313, 
                domain = fdtapi.models.ton_connect_proof_request_proof_domain.tonConnectProof_request_proof_domain(
                    length_bytes = 56, 
                    value = '', ), 
                signature = '', 
                payload = '84jHVNLQmZsAAAAAZB0Zryi2wqVJI-KaKNXOvCijEi46YyYzkaSHyJrMPBMOkVZa', 
                state_init = ''
            )
        else :
            return TonConnectProofRequestProof(
                timestamp = 1678275313,
                domain = fdtapi.models.ton_connect_proof_request_proof_domain.tonConnectProof_request_proof_domain(
                    length_bytes = 56, 
                    value = '', ),
                signature = '',
                payload = '84jHVNLQmZsAAAAAZB0Zryi2wqVJI-KaKNXOvCijEi46YyYzkaSHyJrMPBMOkVZa',
        )
        """

    def testTonConnectProofRequestProof(self):
        """Test TonConnectProofRequestProof"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
