# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.found_accounts import FoundAccounts  # noqa: E501
from fdtapi.rest import ApiException

class TestFoundAccounts(unittest.TestCase):
    """FoundAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FoundAccounts
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FoundAccounts`
        """
        model = fdtapi.models.found_accounts.FoundAccounts()  # noqa: E501
        if include_optional :
            return FoundAccounts(
                addresses = [
                    fdtapi.models.found_accounts_addresses_inner.FoundAccounts_addresses_inner(
                        address = '0:010cеeac44fad23417a5c55e4071796868771082с9a61e8c195a8d57508b8471', 
                        name = 'blah_blah.ton', )
                    ]
            )
        else :
            return FoundAccounts(
                addresses = [
                    fdtapi.models.found_accounts_addresses_inner.FoundAccounts_addresses_inner(
                        address = '0:010cеeac44fad23417a5c55e4071796868771082с9a61e8c195a8d57508b8471', 
                        name = 'blah_blah.ton', )
                    ],
        )
        """

    def testFoundAccounts(self):
        """Test FoundAccounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
