# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.get_staking_pool_history200_response import GetStakingPoolHistory200Response  # noqa: E501
from fdtapi.rest import ApiException

class TestGetStakingPoolHistory200Response(unittest.TestCase):
    """GetStakingPoolHistory200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetStakingPoolHistory200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStakingPoolHistory200Response`
        """
        model = fdtapi.models.get_staking_pool_history200_response.GetStakingPoolHistory200Response()  # noqa: E501
        if include_optional :
            return GetStakingPoolHistory200Response(
                apy = [
                    fdtapi.models.apy_history.ApyHistory(
                        apy = 1.337, 
                        time = 56, )
                    ]
            )
        else :
            return GetStakingPoolHistory200Response(
                apy = [
                    fdtapi.models.apy_history.ApyHistory(
                        apy = 1.337, 
                        time = 56, )
                    ],
        )
        """

    def testGetStakingPoolHistory200Response(self):
        """Test GetStakingPoolHistory200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
