# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.ton_connect_proof_request_proof_domain import TonConnectProofRequestProofDomain  # noqa: E501
from fdtapi.rest import ApiException

class TestTonConnectProofRequestProofDomain(unittest.TestCase):
    """TonConnectProofRequestProofDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TonConnectProofRequestProofDomain
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TonConnectProofRequestProofDomain`
        """
        model = fdtapi.models.ton_connect_proof_request_proof_domain.TonConnectProofRequestProofDomain()  # noqa: E501
        if include_optional :
            return TonConnectProofRequestProofDomain(
                length_bytes = 56, 
                value = ''
            )
        else :
            return TonConnectProofRequestProofDomain(
                value = '',
        )
        """

    def testTonConnectProofRequestProofDomain(self):
        """Test TonConnectProofRequestProofDomain"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
