# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.message import Message  # noqa: E501
from fdtapi.rest import ApiException

class TestMessage(unittest.TestCase):
    """Message unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Message
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Message`
        """
        model = fdtapi.models.message.Message()  # noqa: E501
        if include_optional :
            return Message(
                created_lt = 25713146000001, 
                ihr_disabled = True, 
                bounce = True, 
                bounced = True, 
                value = 60000000, 
                fwd_fee = 5681002, 
                ihr_fee = 5681002, 
                destination = fdtapi.models.account_address.AccountAddress(
                    address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365', 
                    name = 'Ton foundation', 
                    is_scam = True, 
                    icon = 'https://ton.org/logo.png', ), 
                source = fdtapi.models.account_address.AccountAddress(
                    address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365', 
                    name = 'Ton foundation', 
                    is_scam = True, 
                    icon = 'https://ton.org/logo.png', ), 
                import_fee = 5681002, 
                created_at = 5681002, 
                op_code = '0xdeadbeaf', 
                init = fdtapi.models.state_init.StateInit(
                    boc = 'te6ccgEBBgEARAABFP8A9KQT9LzyyAsBAgEgAgMCAUgEBQAE8jAAONBsIdMfMO1E0NM/MAHAAZekyMs/ye1UkzDyBuIAEaE0MdqJoaZ+YQ==', ), 
                raw_body = 'B5EE9C7201010101001100001D00048656C6C6F2C20776F726C64218', 
                decoded_op_name = 'nft_transfer', 
                decoded_body = None
            )
        else :
            return Message(
                created_lt = 25713146000001,
                ihr_disabled = True,
                bounce = True,
                bounced = True,
                value = 60000000,
                fwd_fee = 5681002,
                ihr_fee = 5681002,
                import_fee = 5681002,
                created_at = 5681002,
        )
        """

    def testMessage(self):
        """Test Message"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
