# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.rates_api import RatesApi  # noqa: E501
from fdtapi.rest import ApiException


class TestRatesApi(unittest.TestCase):
    """RatesApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.rates_api.RatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_chart_rates(self):
        """Test case for get_chart_rates

        """
        pass

    def test_get_rates(self):
        """Test case for get_rates

        """
        pass


if __name__ == '__main__':
    unittest.main()
