# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.get_raw_list_block_transactions200_response_ids_inner import GetRawListBlockTransactions200ResponseIdsInner  # noqa: E501
from fdtapi.rest import ApiException

class TestGetRawListBlockTransactions200ResponseIdsInner(unittest.TestCase):
    """GetRawListBlockTransactions200ResponseIdsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetRawListBlockTransactions200ResponseIdsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRawListBlockTransactions200ResponseIdsInner`
        """
        model = fdtapi.models.get_raw_list_block_transactions200_response_ids_inner.GetRawListBlockTransactions200ResponseIdsInner()  # noqa: E501
        if include_optional :
            return GetRawListBlockTransactions200ResponseIdsInner(
                mode = 0, 
                account = '131D0C65055F04E9C19D687B51BC70F952FD9CA6F02C2801D3B89964A779DF85', 
                lt = 56, 
                hash = '131D0C65055F04E9C19D687B51BC70F952FD9CA6F02C2801D3B89964A779DF85'
            )
        else :
            return GetRawListBlockTransactions200ResponseIdsInner(
                mode = 0,
        )
        """

    def testGetRawListBlockTransactions200ResponseIdsInner(self):
        """Test GetRawListBlockTransactions200ResponseIdsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
