# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.jetton_verification_type import JettonVerificationType  # noqa: E501
from fdtapi.rest import ApiException

class TestJettonVerificationType(unittest.TestCase):
    """JettonVerificationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJettonVerificationType(self):
        """Test JettonVerificationType"""
        # inst = JettonVerificationType()

if __name__ == '__main__':
    unittest.main()
