# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.acc_status_change import AccStatusChange  # noqa: E501
from fdtapi.rest import ApiException

class TestAccStatusChange(unittest.TestCase):
    """AccStatusChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccStatusChange(self):
        """Test AccStatusChange"""
        # inst = AccStatusChange()

if __name__ == '__main__':
    unittest.main()
