# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.emulation_api import EmulationApi  # noqa: E501
from fdtapi.rest import ApiException


class TestEmulationApi(unittest.TestCase):
    """EmulationApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.emulation_api.EmulationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_emulate_message_to_account_event(self):
        """Test case for emulate_message_to_account_event

        """
        pass

    def test_emulate_message_to_event(self):
        """Test case for emulate_message_to_event

        """
        pass

    def test_emulate_message_to_trace(self):
        """Test case for emulate_message_to_trace

        """
        pass

    def test_emulate_message_to_wallet(self):
        """Test case for emulate_message_to_wallet

        """
        pass


if __name__ == '__main__':
    unittest.main()
