# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fdtapi
from fdtapi.models.account_address import AccountAddress  # noqa: E501
from fdtapi.rest import ApiException

class TestAccountAddress(unittest.TestCase):
    """AccountAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AccountAddress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountAddress`
        """
        model = fdtapi.models.account_address.AccountAddress()  # noqa: E501
        if include_optional :
            return AccountAddress(
                address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365', 
                name = 'Ton foundation', 
                is_scam = True, 
                icon = 'https://ton.org/logo.png'
            )
        else :
            return AccountAddress(
                address = '0:10C1073837B93FDAAD594284CE8B8EFF7B9CF25427440EB2FC682762E1471365',
                is_scam = True,
        )
        """

    def testAccountAddress(self):
        """Test AccountAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
