# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fdtapi
from fdtapi.api.staking_api import StakingApi  # noqa: E501
from fdtapi.rest import ApiException


class TestStakingApi(unittest.TestCase):
    """StakingApi unit test stubs"""

    def setUp(self):
        self.api = fdtapi.api.staking_api.StakingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_nominators_pools(self):
        """Test case for get_account_nominators_pools

        """
        pass

    def test_get_staking_pool_history(self):
        """Test case for get_staking_pool_history

        """
        pass

    def test_get_staking_pool_info(self):
        """Test case for get_staking_pool_info

        """
        pass

    def test_get_staking_pools(self):
        """Test case for get_staking_pools

        """
        pass


if __name__ == '__main__':
    unittest.main()
