# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AccountStatus(str, Enum):
    """
    AccountStatus
    """

    """
    allowed enum values
    """
    NONEXIST = 'nonexist'
    UNINIT = 'uninit'
    ACTIVE = 'active'
    FROZEN = 'frozen'

    @classmethod
    def from_json(cls, json_str: str) -> AccountStatus:
        """Create an instance of AccountStatus from a JSON string"""
        return AccountStatus(json.loads(json_str))


