# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class AccountAddress(BaseModel):
    """
    AccountAddress
    """
    address: StrictStr = Field(...)
    name: Optional[StrictStr] = Field(None, description="Display name. Data collected from different sources like moderation lists, dns, collections names and over.")
    is_scam: StrictBool = Field(..., description="Is this account was marked as part of scammers activity")
    icon: Optional[StrictStr] = None
    __properties = ["address", "name", "is_scam", "icon"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AccountAddress:
        """Create an instance of AccountAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AccountAddress:
        """Create an instance of AccountAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AccountAddress.parse_obj(obj)

        _obj = AccountAddress.parse_obj({
            "address": obj.get("address"),
            "name": obj.get("name"),
            "is_scam": obj.get("is_scam"),
            "icon": obj.get("icon")
        })
        return _obj

