# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class BouncePhaseType(str, Enum):
    """
    BouncePhaseType
    """

    """
    allowed enum values
    """
    TRPHASEBOUNCENEGFUNDS = 'TrPhaseBounceNegfunds'
    TRPHASEBOUNCENOFUNDS = 'TrPhaseBounceNofunds'
    TRPHASEBOUNCEOK = 'TrPhaseBounceOk'

    @classmethod
    def from_json(cls, json_str: str) -> BouncePhaseType:
        """Create an instance of BouncePhaseType from a JSON string"""
        return BouncePhaseType(json.loads(json_str))


