# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from fdtapi.models.block_raw import BlockRaw

class GetRawBlockchainBlockState200Response(BaseModel):
    """
    GetRawBlockchainBlockState200Response
    """
    id: BlockRaw = Field(...)
    root_hash: StrictStr = Field(...)
    file_hash: StrictStr = Field(...)
    data: StrictStr = Field(...)
    __properties = ["id", "root_hash", "file_hash", "data"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetRawBlockchainBlockState200Response:
        """Create an instance of GetRawBlockchainBlockState200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetRawBlockchainBlockState200Response:
        """Create an instance of GetRawBlockchainBlockState200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetRawBlockchainBlockState200Response.parse_obj(obj)

        _obj = GetRawBlockchainBlockState200Response.parse_obj({
            "id": BlockRaw.from_dict(obj.get("id")) if obj.get("id") is not None else None,
            "root_hash": obj.get("root_hash"),
            "file_hash": obj.get("file_hash"),
            "data": obj.get("data")
        })
        return _obj

