# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
from fdtapi.models.block_raw import BlockRaw
from fdtapi.models.get_raw_list_block_transactions200_response_ids_inner import GetRawListBlockTransactions200ResponseIdsInner

class GetRawListBlockTransactions200Response(BaseModel):
    """
    GetRawListBlockTransactions200Response
    """
    id: BlockRaw = Field(...)
    req_count: StrictInt = Field(...)
    incomplete: StrictBool = Field(...)
    ids: conlist(GetRawListBlockTransactions200ResponseIdsInner) = Field(...)
    proof: StrictStr = Field(...)
    __properties = ["id", "req_count", "incomplete", "ids", "proof"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetRawListBlockTransactions200Response:
        """Create an instance of GetRawListBlockTransactions200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ids (list)
        _items = []
        if self.ids:
            for _item in self.ids:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ids'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetRawListBlockTransactions200Response:
        """Create an instance of GetRawListBlockTransactions200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetRawListBlockTransactions200Response.parse_obj(obj)

        _obj = GetRawListBlockTransactions200Response.parse_obj({
            "id": BlockRaw.from_dict(obj.get("id")) if obj.get("id") is not None else None,
            "req_count": obj.get("req_count"),
            "incomplete": obj.get("incomplete"),
            "ids": [GetRawListBlockTransactions200ResponseIdsInner.from_dict(_item) for _item in obj.get("ids")] if obj.get("ids") is not None else None,
            "proof": obj.get("proof")
        })
        return _obj

