# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from fdtapi.models.block_raw import BlockRaw
from fdtapi.models.get_raw_shard_block_proof200_response_links_inner import GetRawShardBlockProof200ResponseLinksInner

class GetRawShardBlockProof200Response(BaseModel):
    """
    GetRawShardBlockProof200Response
    """
    masterchain_id: BlockRaw = Field(...)
    links: conlist(GetRawShardBlockProof200ResponseLinksInner) = Field(...)
    __properties = ["masterchain_id", "links"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetRawShardBlockProof200Response:
        """Create an instance of GetRawShardBlockProof200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of masterchain_id
        if self.masterchain_id:
            _dict['masterchain_id'] = self.masterchain_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['links'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetRawShardBlockProof200Response:
        """Create an instance of GetRawShardBlockProof200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetRawShardBlockProof200Response.parse_obj(obj)

        _obj = GetRawShardBlockProof200Response.parse_obj({
            "masterchain_id": BlockRaw.from_dict(obj.get("masterchain_id")) if obj.get("masterchain_id") is not None else None,
            "links": [GetRawShardBlockProof200ResponseLinksInner.from_dict(_item) for _item in obj.get("links")] if obj.get("links") is not None else None
        })
        return _obj

