# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from fdtapi.models.account_address import AccountAddress
from fdtapi.models.jetton_preview import JettonPreview

class JettonQuantity(BaseModel):
    """
    JettonQuantity
    """
    quantity: StrictStr = Field(...)
    wallet_address: AccountAddress = Field(...)
    jetton: JettonPreview = Field(...)
    __properties = ["quantity", "wallet_address", "jetton"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> JettonQuantity:
        """Create an instance of JettonQuantity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of wallet_address
        if self.wallet_address:
            _dict['wallet_address'] = self.wallet_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of jetton
        if self.jetton:
            _dict['jetton'] = self.jetton.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> JettonQuantity:
        """Create an instance of JettonQuantity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return JettonQuantity.parse_obj(obj)

        _obj = JettonQuantity.parse_obj({
            "quantity": obj.get("quantity"),
            "wallet_address": AccountAddress.from_dict(obj.get("wallet_address")) if obj.get("wallet_address") is not None else None,
            "jetton": JettonPreview.from_dict(obj.get("jetton")) if obj.get("jetton") is not None else None
        })
        return _obj

