# coding: utf-8

"""
    REST api to TON blockchain explorer

    Provide access to indexed TON blockchain  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@tonkeeper.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from fdtapi.models.account_address import AccountAddress

class UnSubscriptionAction(BaseModel):
    """
    UnSubscriptionAction
    """
    subscriber: AccountAddress = Field(...)
    subscription: StrictStr = Field(...)
    beneficiary: AccountAddress = Field(...)
    __properties = ["subscriber", "subscription", "beneficiary"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UnSubscriptionAction:
        """Create an instance of UnSubscriptionAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of subscriber
        if self.subscriber:
            _dict['subscriber'] = self.subscriber.to_dict()
        # override the default output from pydantic by calling `to_dict()` of beneficiary
        if self.beneficiary:
            _dict['beneficiary'] = self.beneficiary.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UnSubscriptionAction:
        """Create an instance of UnSubscriptionAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UnSubscriptionAction.parse_obj(obj)

        _obj = UnSubscriptionAction.parse_obj({
            "subscriber": AccountAddress.from_dict(obj.get("subscriber")) if obj.get("subscriber") is not None else None,
            "subscription": obj.get("subscription"),
            "beneficiary": AccountAddress.from_dict(obj.get("beneficiary")) if obj.get("beneficiary") is not None else None
        })
        return _obj

